export const DATA = [
  { character: "The Lone Ranger and Tonto", song: "Bob Dylan’s Blues", quote: "Well, the Lone Ranger and Tonto, they are ridin’ down the line / Fixin’ ev’rybody’s troubles, ev’rybody’s ’cept mine" },
  { character: "A Poet Who Died in the Gutter", song: "A Hard Rain’s A-Gonna Fall", quote: "Heard the song of a poet who died in the gutter / Heard the sound of a clown who cried in the alley" },
  { character: "A Clown Who Cried in the Alley", song: "A Hard Rain’s A-Gonna Fall", quote: "Heard the song of a poet who died in the gutter / Heard the sound of a clown who cried in the alley" },
  { character: "The Great-Granddaughter of Mr. Clean", song: "I Shall Be Free", quote: "Well, the funniest woman I ever seen / Was the great-granddaughter of Mr. Clean" },
  { character: "President Kennedy", song: "I Shall Be Free", quote: "Well, my telephone rang it would not stop / It’s President Kennedy callin’ me up" },
  { character: "Medgar Evers", song: "Only a Pawn in Their Game", quote: "A bullet from the back of a bush took Medgar Evers’ blood / A finger fired the trigger to his name" },
  { character: "Goliath", song: "When the Ship Comes In", quote: "And like Pharoah’s tribe / They’ll be drownded in the tide / And like Goliath, they’ll be conquered" },
  { character: "William Zanzinger", song: "The Lonesome Death of Hattie Carroll", quote: "William Zanzinger killed poor Hattie Carroll / With a cane that he twirled around his diamond ring finger" },
  { character: "Gypsy Gal", song: "Spanish Harlem Incident", quote: "Gypsy gal, the hands of Harlem / Cannot hold you to its heat" },
  { character: "The Misdemeanor Outlaw", song: "Chimes of Freedom", quote: "For the misdemeanor outlaw, chased an’ cheated by pursuit / An’ we gazed upon the chimes of freedom flashing" },
  { character: "The Mistitled Prostitute", song: "Chimes of Freedom", quote: "Tolling for the deaf an’ blind, tolling for the mute / Tolling for the mistreated, mateless mother, the mistitled prostitute" },
  { character: "Cassius Clay", song: "I Shall Be Free No. 10", quote: "I was shadow-boxing earlier in the day / I figured I was ready for Cassius Clay" },
  { character: "Barry Goldwater", song: "I Shall Be Free No. 10", quote: "But if you think that I’ll let Barry Goldwater / Move in next door and marry my daughter / You must think I’m crazy!" },
  { character: "Fidel Castro", song: "Motorpsycho Nightmare", quote: "I had to say something / To strike him very weird / So I yelled out / \"I like Fidel Castro and his beard\"" },
  { character: "The Vandals", song: "Subterranean Homesick Blues", quote: "The pump don’t work / ’Cause the vandals took the handles" },
  { character: "The Man in the Trench Coat", song: "Subterranean Homesick Blues", quote: "The man in the trench coat / Badge out, laid off / Says he’s got a bad cough / Wants to get it paid off" },
  { character: "Captain Arab", song: "Bob Dylan’s 115th Dream", quote: "I was riding on the Mayflower / When I thought I spied some land / I yelled for Captain Arab / I have yuh understand" },
  { character: "The Gray Flannel Dwarf", song: "Gates of Eden", quote: "The motorcycle black madonna / Two-wheeled gypsy queen / And her silver-studded phantom cause / The gray flannel dwarf to scream" },
  { character: "The Vagabond Who’s Rapping at Your Door", song: "It’s All Over Now, Baby Blue", quote: "The vagabond who’s rapping at your door / Is standing in the clothes that you once wore" },
  { character: "The Empty-Handed Painter from Your Streets", song: "It’s All Over Now, Baby Blue", quote: "The empty-handed painter from your streets / Is drawing crazy patterns on your sheets" },
  { character: "The Jugglers and the Clowns", song: "Like a Rolling Stone", quote: "You never turned around to see the frowns on the jugglers and the clowns / When they all come down and did tricks for you" },
  { character: "Napoleon in Rags", song: "Like a Rolling Stone", quote: "You used to be so amused / At Napoleon in rags and the language that he used" },
  { character: "The King of the Philistines", song: "Tombstone Blues", quote: "The king of the Philistines his soldiers to save / Puts jawbones on their tombstones and flatters their graves" },
  { character: "Gypsy Davey", song: "Tombstone Blues", quote: "Gypsy Davey with a blowtorch he burns out their camps / With his faithful slave Pedro behind him he tramps" },
  { character: "The Brakeman", song: "It Takes a Lot to Laugh, It Takes a Train to Cry", quote: "Don’t the brakeman look good, mama / Flagging down the \"Double E?\"" },
  { character: "A Junkyard Angel", song: "From a Buick 6", quote: "She’s a junkyard angel and she always gives me bread / Well, if I go down dyin’, you know she bound to put a blanket on my bed." },
  { character: "Mister Jones", song: "Ballad of a Thin Man", quote: "Because something is happening here / But you don’t know what it is / Do you, Mister Jones?" },
  { character: "The Sword Swallower", song: "Ballad of a Thin Man", quote: "Well, the sword swallower, he comes up to you / And then he kneels" },
  { character: "The Flower Ladies", song: "Queen Jane Approximately", quote: "Now when all of the flower ladies want back what they have lent you / And the smell of their roses does not remain" },
  { character: "Georgia Sam", song: "Highway 61 Revisited", quote: "Well Georgia Sam he had a bloody nose / Welfare Department they wouldn’t give him no clothes" },
  { character: "Mack the Finger", song: "Highway 61 Revisited", quote: "Well Mack the Finger said to Louie the King / I got forty red white and blue shoestrings" },
  { character: "Saint Annie", song: "Just Like Tom Thumb’s Blues", quote: "Now if you see Saint Annie / Please tell her thanks a lot / I cannot move / My fingers are all in a knot" },
  { character: "Sweet Melinda", song: "Just Like Tom Thumb’s Blues", quote: "Sweet Melinda / The peasants call her the goddess of gloom / She speaks good English / And she invites you up into her room" },
  { character: "The Fortune-Telling Lady", song: "Desolation Row", quote: "The fortune-telling lady / Has even taken all her things inside" },
  { character: "Ezra Pound & T.S. Eliot", song: "Desolation Row", quote: "And Ezra Pound and T. S. Eliot / Fighting in the captain’s tower" },
  { character: "Louise and Her Lover", song: "Visions of Johanna", quote: "Just Louise and her lover so entwined / And these visions of Johanna that conquer my mind" },
  { character: "Little Boy Lost", song: "Visions of Johanna", quote: "Now, little boy lost, he takes himself so seriously / He brags of his misery, he likes to live dangerously" },
  { character: "The Guilty Undertaker", song: "I Want You", quote: "The guilty undertaker sighs / The lonesome organ grinder cries" },
  { character: "The Drunken Politician", song: "I Want You", quote: "The drunken politician leaps / Upon the street where mothers weep" },
  { character: "The Ragman", song: "Stuck Inside of Mobile with the Memphis Blues Again", quote: "Oh, the ragman draws circles / Up and down the block / I’d ask him what the matter was / But I know that he don’t talk" },
  { character: "Some French Girl", song: "Stuck Inside of Mobile with the Memphis Blues Again", quote: "Well, Shakespeare, he’s in the alley / With his pointed shoes and his bells / Speaking to some French girl / Who says she knows me well" },
  { character: "Queen Mary", song: "Just Like a Woman", quote: "Queen Mary, she’s my friend / Yes, I believe I’ll go see her again" },
  { character: "The Persian Drunkard", song: "Absolutely Sweet Marie", quote: "Well, I got the fever down in my pockets / The Persian drunkard, he follows me" },
  { character: "The Kings of Tyrus", song: "Sad-Eyed Lady of the Lowlands", quote: "The kings of Tyrus with their convict list / Are waiting in line for their geranium kiss" },
] as const;

export type QuizEntry = (typeof DATA)[number];

export const ALL_SONGS = [...new Set(DATA.map((d) => d.song))];
